Fix evaluation of link-less anchor tags
pelican-plugins/seo pull request #28
Opened 2020-11-24 12:49 UTC by kdeldycke

When the SEO plugin encounter this kind of tags:

```html
<a name="L-1"></a>
```

It fails with that traceback:

```pythontb
CRITICAL: 'href'
Traceback (most recent call last):
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/__init__.py", line 512, in main
    pelican.run()
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/__init__.py", line 115, in run
    signals.all_generators_finalized.send(generators)
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo.py", line 64, in run_seo_report
    seo_report.generate(site_name=site_name, documents_analysis=documents_analysis)
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo_report/__init__.py", line 242, in generate
    document_report = self._launch_report(document_analysis)
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo_report/__init__.py", line 220, in _launch_report
    internal_link_report = self._internal_link_report(
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo_report/__init__.py", line 182, in _internal_link_report
    internal_link_occurrence = internal_link_analysis.internal_link_occurrence
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo_report/seo_analyzer/internal_link_analyzer.py", line 33, in internal_link_occurrence
    return len([link for link in self._links if self._siteurl in link["href"]])
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/pelican/plugins/seo/seo_report/seo_analyzer/internal_link_analyzer.py", line 33, in <listcomp>
    return len([link for link in self._links if self._siteurl in link["href"]])
  File "/Users/kde/Library/Caches/pypoetry/virtualenvs/blog-Nb0Mdndq-py3.8/lib/python3.8/site-packages/bs4/element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'href'
```

This PR fix this issue.

2020-11-24 17:05 UTC, MaevaBrunelles commented
Hi @kdeldycke,

I didn't expect to have a usecase with the `a` tag without `href`, that's why at that time I didn't find relevant to catch any `KeyError`.

Your PR indeed fix the bug, but I will do it differently:
- Update `self._links = self._soup.find_all("a")` by adding the parameter `href=True` -> `self._links = self._soup.find_all("a", href=True)`. It'll avoid to loop on `a` tags that we don't care. Here we are on class which works only with links.
- Update the conftest [here](https://github.com/pelican-plugins/seo/blob/master/pelican/plugins/seo/tests/conftest.py#L88) to add a fourth `a` tag but without `href`, for example `<a>a tag without href attribute</a>`
- Update [this test](https://github.com/pelican-plugins/seo/blob/master/pelican/plugins/seo/tests/test_internal_link_analyzer.py#L32) to assert that `len(fake_analysis.internal_link_occurrence` is still equal to `2` AND not equal to `4`.

2020-11-26 09:55 UTC, kdeldycke commented
Thanks @MaevaBrunelles for the detailed review! I applied all your proposed changes. This PR is ready to be merged! :)

2020-11-27 17:41 UTC, MaevaBrunelles requested changes
My bad, I pointed the wrong fixture. It's `fake_article_multiple_elements` which need an update, as it's this fixture which is used in the concerned test.
I hope that with GitHub suggestions it woulb be easier to update the PR.

2020-11-27 17:41 UTC, MaevaBrunelles commented on pelican/plugins/seo/tests/conftest.py
> +                        <a>a tag without href attribute</a>
```suggestion
```

2020-11-27 17:41 UTC, MaevaBrunelles commented on pelican/plugins/seo/tests/conftest.py
> +                        </pre>
```suggestion
                        <a>a tag without href attribute</a>
```

2020-11-27 17:41 UTC, MaevaBrunelles commented on pelican/plugins/seo/tests/test_seo_enhancer.py
> +  </a>
```suggestion
```

2020-11-27 18:22 UTC, kdeldycke commented
No worries! All done. Ready to merge! :)

2020-11-27 19:14 UTC, merged

2020-11-27 19:22 UTC, MaevaBrunelles commented
Thanks again for your PR!